# Autogenerated using ProtoBuf.jl v1.0.9 on 2023-03-01T12:24:36.205
# original file: /home/tj/workspace/git/OpenTelemetry.jl/src/proto/dev/opentelemetry-proto-0.19.0/opentelemetry/proto/collector/metrics/v1/metrics_service.proto (proto3 syntax)

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export ExportMetricsServiceRequest, ExportMetricsPartialSuccess
export ExportMetricsServiceResponse, MetricsService

struct ExportMetricsServiceRequest
    resource_metrics::Vector{opentelemetry.proto.metrics.v1.ResourceMetrics}
end
PB.default_values(::Type{ExportMetricsServiceRequest}) = (;resource_metrics = Vector{opentelemetry.proto.metrics.v1.ResourceMetrics}())
PB.field_numbers(::Type{ExportMetricsServiceRequest}) = (;resource_metrics = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ExportMetricsServiceRequest})
    resource_metrics = PB.BufferedVector{opentelemetry.proto.metrics.v1.ResourceMetrics}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, resource_metrics)
        else
            PB.skip(d, wire_type)
        end
    end
    return ExportMetricsServiceRequest(resource_metrics[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ExportMetricsServiceRequest)
    initpos = position(e.io)
    !isempty(x.resource_metrics) && PB.encode(e, 1, x.resource_metrics)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ExportMetricsServiceRequest)
    encoded_size = 0
    !isempty(x.resource_metrics) && (encoded_size += PB._encoded_size(x.resource_metrics, 1))
    return encoded_size
end

struct ExportMetricsPartialSuccess
    rejected_data_points::Int64
    error_message::String
end
PB.default_values(::Type{ExportMetricsPartialSuccess}) = (;rejected_data_points = zero(Int64), error_message = "")
PB.field_numbers(::Type{ExportMetricsPartialSuccess}) = (;rejected_data_points = 1, error_message = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ExportMetricsPartialSuccess})
    rejected_data_points = zero(Int64)
    error_message = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            rejected_data_points = PB.decode(d, Int64)
        elseif field_number == 2
            error_message = PB.decode(d, String)
        else
            PB.skip(d, wire_type)
        end
    end
    return ExportMetricsPartialSuccess(rejected_data_points, error_message)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ExportMetricsPartialSuccess)
    initpos = position(e.io)
    x.rejected_data_points != zero(Int64) && PB.encode(e, 1, x.rejected_data_points)
    !isempty(x.error_message) && PB.encode(e, 2, x.error_message)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ExportMetricsPartialSuccess)
    encoded_size = 0
    x.rejected_data_points != zero(Int64) && (encoded_size += PB._encoded_size(x.rejected_data_points, 1))
    !isempty(x.error_message) && (encoded_size += PB._encoded_size(x.error_message, 2))
    return encoded_size
end

struct ExportMetricsServiceResponse
    partial_success::Union{Nothing,ExportMetricsPartialSuccess}
end
PB.default_values(::Type{ExportMetricsServiceResponse}) = (;partial_success = nothing)
PB.field_numbers(::Type{ExportMetricsServiceResponse}) = (;partial_success = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ExportMetricsServiceResponse})
    partial_success = Ref{Union{Nothing,ExportMetricsPartialSuccess}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, partial_success)
        else
            PB.skip(d, wire_type)
        end
    end
    return ExportMetricsServiceResponse(partial_success[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ExportMetricsServiceResponse)
    initpos = position(e.io)
    !isnothing(x.partial_success) && PB.encode(e, 1, x.partial_success)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ExportMetricsServiceResponse)
    encoded_size = 0
    !isnothing(x.partial_success) && (encoded_size += PB._encoded_size(x.partial_success, 1))
    return encoded_size
end

# TODO: SERVICE
#    MetricsService
