global:
  scrape_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: OpenTelemetry.jl_tutorial_metrics
    metrics_path: /
    static_configs:
      - targets:
          - 'host.docker.internal:9966'