version: '3'

services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:0.45.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-config-jaeger.yml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"        # OTLP gRPC receiver
