receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true

service:
  pipelines:
    logs:
      receivers:
        - otlp
      exporters:
        - loki
    traces:
      receivers:
        - otlp
      exporters:
        - otlp
    metrics:
      receivers:
        - otlp
      exporters:
        - prometheus
