name = "OpenTelemetryInstrumentationBase"
uuid = "4046903c-540b-416b-9793-ac8011f4a0e0"
authors = ["Jun Tian <tianjun.cpp@gmail.com>"]
version = "0.1.0"

[deps]
OpenTelemetryAPI = "4f63ef3d-5940-44e7-a611-2d97696cffc9"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
